{% set name = "aiida-gaussian" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-gaussian-{{ version }}.tar.gz
  sha256: 3ed1983339843ae26baf073608f9faf34d2c32161bd3174d2f05c69c9523771f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - reentry
  run:
    - aiida-core >=1.0.0,<2.0.0
    - ase
    - cclib >=1.6.1,<=1.7
    # pandas has broken builds: https://github.com/conda-forge/pandas-feedstock/issues/137
    - pandas !=1.4.0,!=1.4.1,!=1.4.2
    - pymatgen >=2020.4,<2022.0.0
    - python >=3.7

test:
  imports:
    - aiida_gaussian
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nanotech-empa/aiida-gaussian
  summary: AiiDA plugin for the Gaussian quantum chemistry software
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
